# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Data_log_GUI_R0.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from PyQt5.uic import loadUi
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QApplication


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1187, 797)
        MainWindow.setMaximumSize(QtCore.QSize(1187, 797))
        MainWindow.setStyleSheet("QMainWindow{\n"
                "background:rgb(255, 255, 127);\n"
                "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(480, 10, 241, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 10, 61, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.tabLog = QtWidgets.QTableWidget(self.centralwidget)
        self.tabLog.setGeometry(QtCore.QRect(10, 50, 1161, 711))
        self.tabLog.setStyleSheet("QTableWidget{\n"
                "background: rgb(85, 255, 255);\n"
                "color: black;\n"
                "}")
        self.tabLog.setObjectName("tabLog")
        self.tabLog.setColumnCount(8)
        self.tabLog.setRowCount(0)
        self.tabLog.setColumnWidth(0,70)
        self.tabLog.setColumnWidth(1,110)
        self.tabLog.setColumnWidth(2,110)
        self.tabLog.setColumnWidth(3,100)
        self.tabLog.setColumnWidth(4,200)
        self.tabLog.setColumnWidth(5,110)
        self.tabLog.setColumnWidth(6,350)
        self.tabLog.setColumnWidth(7,110)
        self.loaddata()
 
    def loaddata(self):

        people=[{"Sr.No.":"1","Date":"09/05/2024","Start Time":"08:04:00.353 ","End Time":"10:04:00.343 ","Error Code":"0001","Type":"User Generated","Description":"EmgStopPressed","Status":"NA"},
                {"Sr.No.":"2","Date":"09/05/2024","Start Time":"06:04:00.340 ","End Time":"08:04:00.343 ","Error Code":"0001","Type":"User Generated","Description":"EmgStopPressed","Status":"NA"}]
        row=0
        for person in people:
                self.tabLog.setRowCount(len(people))
                self.tabLog.setItem(row, 0, QtWidgets.QTableWidgetItem(person["Sr.No."]))
                self.tabLog.setItem(row, 1, QtWidgets.QTableWidgetItem(person["Date"]))
                self.tabLog.setItem(row, 2, QtWidgets.QTableWidgetItem(person["Start Time"]))
                self.tabLog.setItem(row, 3, QtWidgets.QTableWidgetItem(person["End Time"]))
                self.tabLog.setItem(row, 4, QtWidgets.QTableWidgetItem(person["Error Code"]))
                self.tabLog.setItem(row, 5, QtWidgets.QTableWidgetItem(person["Type"]))
                self.tabLog.setItem(row, 6, QtWidgets.QTableWidgetItem(person["Description"]))
                self.tabLog.setItem(row, 7, QtWidgets.QTableWidgetItem(person["Status"]))
                row=row+1



        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 0, 0))
        self.tabLog.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tabLog.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tabLog.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tabLog.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tabLog.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tabLog.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tabLog.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tabLog.setHorizontalHeaderItem(7, item)
        self.txtPLCIP = QtWidgets.QTextEdit(self.centralwidget)
        self.txtPLCIP.setGeometry(QtCore.QRect(80, 10, 141, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPLCIP.sizePolicy().hasHeightForWidth())
        self.txtPLCIP.setSizePolicy(sizePolicy)
        self.txtPLCIP.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.txtPLCIP.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.txtPLCIP.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.txtPLCIP.setAutoFormatting(QtWidgets.QTextEdit.AutoBulletList)
        self.txtPLCIP.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.txtPLCIP.setObjectName("txtPLCIP")
        self.BtnConnect = QtWidgets.QPushButton(self.centralwidget)
        self.BtnConnect.setGeometry(QtCore.QRect(230, 10, 93, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BtnConnect.setFont(font)
        self.BtnConnect.setAutoFillBackground(False)
        self.BtnConnect.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 255, 0);\n"
"    color: black;\n"
"\n"
"}\n"
"")
        self.BtnConnect.setDefault(False)
        self.BtnConnect.setObjectName("BtnConnect")
        self.Btnlog = QtWidgets.QPushButton(self.centralwidget)
        self.Btnlog.setGeometry(QtCore.QRect(870, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btnlog.setFont(font)
        self.Btnlog.setAutoFillBackground(True)
        self.Btnlog.setDefault(False)
        self.Btnlog.setObjectName("Btnlog")
        self.BtnArch = QtWidgets.QPushButton(self.centralwidget)
        self.BtnArch.setGeometry(QtCore.QRect(970, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BtnArch.setFont(font)
        self.BtnArch.setAutoFillBackground(True)
        self.BtnArch.setDefault(False)
        self.BtnArch.setObjectName("BtnArch")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">DATA LOG APPLICATION</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">PLC IP</span></p></body></html>"))
        item = self.tabLog.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sr. No."))
        item = self.tabLog.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tabLog.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Start Time"))
        item = self.tabLog.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "End Time"))
        item = self.tabLog.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Error Code"))
        item = self.tabLog.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Type"))
        item = self.tabLog.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tabLog.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Status"))
        self.txtPLCIP.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">192.168.XX.XX</span></p></body></html>"))
        self.BtnConnect.setText(_translate("MainWindow", "CONNECT"))
        self.Btnlog.setText(_translate("MainWindow", "LOG"))
        self.BtnArch.setText(_translate("MainWindow", "ARCHIVE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
